name: fluttercleanarchitecture
description: "A new Flutter project."
publish_to: 'none'
version: 0.1.0

environment:
  sdk: ^3.7.0

dependencies:
  flutter:
    sdk: flutter

  # https://pub.dev/packages/flutter_riverpod
  flutter_riverpod: ^2.6.1

  # https://pub.dev/packages/riverpod_annotation
  riverpod_annotation: ^2.6.1

  # https://pub.dev/packages/go_router
  go_router: ^14.8.1

  # https://pub.dev/packages/retrofit
  retrofit: ^4.4.2

  # https://pub.dev/packages/dio
  dio: ^5.7.0
  # https://pub.dev/packages/dio_http_formatter
  dio_http_formatter: ^3.2.1

  # https://pub.dev/packages/freezed_annotation
  freezed_annotation: ^2.4.4

  # https://pub.dev/packages/json_annotation
  json_annotation: ^4.9.0

  # intl: ^0.20.2
  intl: ^0.20.2

  # https://pub.dev/packages/google_fonts
  google_fonts: ^6.2.1
  
  # https://pub.dev/packages/cupertino_icons
  cupertino_icons: ^1.0.8

  # https://pub.dev/packages/flutter_secure_storage
  flutter_secure_storage: ^9.2.4

  # https://pub.dev/packages/flutter_svg
  flutter_svg: ^2.0.17
  
  # https://pub.dev/packages/multiple_result
  multiple_result: ^5.1.0

  # https://pub.dev/packages/youtube_player_flutter
  youtube_player_flutter: ^9.1.1

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0

  # https://pub.dev/packages/build_runner
  build_runner: ^2.4.15

  # https://pub.dev/packages/retrofit_generator
  retrofit_generator: ^9.1.9

  # https://pub.dev/packages/json_serializable
  json_serializable: ^6.9.4

  # https://pub.dev/packages/freezed
  freezed: ^2.5.7

  # https://pub.dev/packages/riverpod_generator
  riverpod_generator: ^2.6.2

  # https://pub.dev/packages/flutter_gen_runner
  flutter_gen_runner: ^5.8.0



flutter_gen:
  output: lib/gen/ # Optional (default: lib/gen/)
  line_length: 80 # Optional (default: 80)

  # Optional
  integrations:
    flutter_svg: true

flutter:
  uses-material-design: true
  assets:
    - assets/images/
